// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "matrix.h"

/////////////////////////////////////////////////////////////////////////////
// CMatrix

IMPLEMENT_DYNCREATE(CMatrix, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMatrix properties

/////////////////////////////////////////////////////////////////////////////
// CMatrix operations

void CMatrix::Reset()
{
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMatrix::GetData(LPUNKNOWN p)
{
	static BYTE parms[] =
		VTS_UNKNOWN;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 p);
}
